### ISSUE TITLE
BuildNeon() is (probably) buggy on MacOS M*

### ISSUE THREAD

**Issue by DavidPeicho** [jbikker/tinybvh#61]
Building a Wald `BVH` works as expected on M3. However, building other BVHs doesn't work with the default `Build` method because it calls `BVH::BuildDefault`, which calls `BVH::BuildNeon` on my M3.

No matter what I pass to `BVH::BuildNeon`, I get 2 `usedNodes` as a result. Tried two separated triangles, tried a sphere with 32x16 segments, and I always get 2 nodes. Obviously, this works using the Wald BVH via `Build()`.

I will try to have a deeper look at what is happening, but right now I wanted to document that somewhere.

**Comment by DavidPeicho** [comment]
Quickly gave it a shot:
* [splitCost](https://github.com/jbikker/tinybvh/blob/44464f51e0f75cf2ebecb08537b79627875b56ea/tiny_bvh.h#L4362) is always `BVH_FAR`
* That's due to an error somewhere in the [ANLR](https://github.com/jbikker/tinybvh/blob/44464f51e0f75cf2ebecb08537b79627875b56ea/tiny_bvh.h#L4353) computation

Will have another look later

**Comment by jbikker** [comment]
Ow if you can help with that that would be great.. That could be a difficult one for me, since I didn't write that code and I don't have a Mac to test on either. Perhaps we can set the default builder for Mac to BVH::Build for the time being, so it's at least correct?

**Comment by jbikker** [comment]
Wait, are you getting the crash on the scene used in tiny_bvh_pt? I found that that scene sometimes yields bin indices outside the valid range. The AVX builder therefore clamps these, but that was a recent change that didn't get implemented in the NEON version. I can make a quick-but-ugly fix.

**Comment by jbikker** [comment]
I pushed a potential fix. This needs to be done with NEON code for performance, but this solution should be reasonable, with limited performance impact: I'm guessing bandwidth is the limiting factor here anyway. Let me know if this helps.

**Comment by DavidPeicho** [comment]
I was just using `BuildNeon` instead of `Build` in the renderer example. I am still getting an infinite loop. Will have a look later :)

**Comment by jbikker** [comment]
I synced in another safety measure from the AVX builder. Perhaps this helps. I need to figure out why it is needed though.

**Comment by DavidPeicho** [comment]
Running the renderer example with a BuildNeon is still infinite looping during intersection [here](https://github.com/jbikker/tinybvh/blob/main/tiny_bvh.h#L1655)

**Comment by jbikker** [comment]
Yes, it would loop indefinitely (at least it will appear as such) if one node has all the primitives.
I did some digging and tried to compile the code on Raspberry, but this failed: The NEON code is using recent intrinsics which are not trivial to emulate. I disabled the NEON builder for now; Mac will now use the regular Build option. I think we should also push this to main for the time being.

**Comment by benanil** [comment]
I think the problem is about implicit register conversion, it trying to xor the float for example but we cannot do that.

**Comment by TheSFReader** [comment]
Since it looks that the NEON build has been entirely removed for now, couldn't you close this issue Jacco ?

**Comment by jbikker** [comment]
Well the Neon code is by @wuyakuma ; I was hoping for a fix so I am a bit reluctant to simply delete the chunk..

**Comment by wuyakuma** [comment]
Wow, I hadn't noticed this issue. I hope to find some free time this weekend to work on it.
Is there any additional information available to help reproduce these bugs?

**Comment by benanil** [comment]
> Wow, I hadn't noticed this issue. I hope to find some free time this weekend to work on it.
> Is there any additional information available to help reproduce these bugs?

To reproduce use different compiler than yours.

You don't see an error because your compiler doesnt recognize implicit vector type conversions as errors

**Comment by wuyakuma** [comment]
Okay, I just created the pull request. The problem seems to be caused by some float/int conversions, particularly due to the different rounding behaviors between _mm_cvtps_epi32 and vcvtq_s32_f32.

The new BuildNEON is tested on fenster/renderer/speedtest with default settings, if there are any more problems, please let me know.

**Comment by jbikker** [comment]
@DavidPeicho : fixed NEON code has been provided by @wuyakuma ; can you confirm this works on your end as well? Then I can close this issue and merge the NEON code back into main.

**Comment by jbikker** [comment]
No problem! In the meantime I have pushed this to main, as I believe quite a few users benefit from this functionality.

**Comment by DavidPeicho** [comment]
@jbikker Tried `BuildNeon` on the fenster example, worked like a charm. Thanks! (also to @wuyakuma)

**Comment by benanil** [comment]
Can anybody check Afra intersections with arm device?
I wrote that part but wasn't able to test because I don't have arm device.
%95 it works
